---
 - debug:
     var: hostvars['localhost']['current_failed_hosts']

 - set_fact:
    current_failed_hosts: "{{  [ inventory_hostname ] + hostvars['localhost']['current_failed_hosts'] }}"
    current_success_hosts_list: "{{ success_hosts_list | reject('search', inventory_hostname) | list }}"
   delegate_to: localhost
