---
 - debug:
     msg: "{{ hostvars }}"

 - debug:
     msg: "{{ hostvars['localhost'] }}"
     
 - set_fact:
    current_failed_hosts: "{{  [ inventory_hostname ] + current_failed_hosts }}"
    current_success_hosts_list: "{{ success_hosts_list | reject('search', inventory_hostname) | list }}"
   delegate_to: localhost
   delegate_facts: true

