---
- set_fact:
    curr_failed_hosts: "{{ curr_failed_hosts + item }}"
  loop: "{{ lookup('file', '/tmp/failedHosts').splitlines() }}"
 
- debug:
    msg: "{{ curr_failed_hosts }}"
    
#  - set_stats:
#      data:
#        success_hosts_list: "{{ current_success_hosts_list }}"
#        failed_jobs: "{{ failed_jobs + [{ patch_job: current_failed_hosts }]  }}"
#      aggregate: no
#    delegate_to: localhost 
