---
- set_fact:
    current_failed_hosts: "{{ current_failed_hosts + [ item ] }}"
  loop: "{{ lookup('file', '/tmp/failedHosts.txt').splitlines() }}"
  delegate_to: localhost

- set_stats:
    data:
      success_hosts_list: "{{ current_success_hosts_list | difference(current_failed_hosts) }}"
      failed_jobs: "{{ failed_jobs + [{ patch_job: current_failed_hosts }]  }}"
    aggregate: no
  delegate_to: localhost 
