---

- set_fact:
    file_lines: "{{ lookup('file', '/tmp/failedHosts.txt').splitlines() }}"
  delegate_to: localhost

- debug:
    msg: "{{ file_lines }}"

- set_fact:
    curr_failed_hosts: "{{ curr_failed_hosts + [ item ] }}"
  with_items: file_lines
  delegate_to: localhost

- debug:
    var: curr_failed_hosts
    
# - set_fact:
#     curr_failed_hosts: !unsafe "{{ curr_failed_hosts + [ item ] }}"
#   loop: "{{ lookup('file', '/tmp/failedHosts.txt').splitlines() }}"
#   delegate_to: localhost


# - set_stats:
#     data:
#       success_hosts_list: "{{ current_success_hosts_list }}"
#       failed_jobs: "{{ failed_jobs + [{ patch_job: curr_failed_hosts }]  }}"
#     aggregate: no
#   delegate_to: localhost
