---
- shell: cat /tmp/failedHosts.txt
  delegate_to: localhost

- set_fact:
    curr_failed_hosts: "{{ curr_failed_hosts + item }}"
  delegate_to: localhost


# - set_fact:
#     curr_failed_hosts: !unsafe "{{ curr_failed_hosts + item }}"
#   loop: "{{ lookup('file', '/tmp/failedHosts.txt').splitlines() }}"
#   delegate_to: localhost


# - set_stats:
#     data:
#       success_hosts_list: "{{ current_success_hosts_list }}"
#       failed_jobs: "{{ failed_jobs + [{ patch_job: curr_failed_hosts }]  }}"
#     aggregate: no
#   delegate_to: localhost 
