---
- hosts: all
  gather_facts: no
  tasks:
    - name: remove from unpatched
      uri:
        url: 'http://34.125.85.2/api/v2/hosts/2/'
        method: PUT
        body:
          '{ "variables": "{ "bla": "sdf" }", "name": "127.0.0.1" }'
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer xq2Xk2ENyuSm9o4MgX0dqQ7gg6J4JO"
        validate_certs: no
        status_code: 204
      delegate_to: localhost


               
