---
- hosts: all
  gather_facts: no
  tasks:
    - name: remove from unpatched
      uri:
        url: 'http://{{ tower_url }}/api/v2/groups/{{ inventory_hostname }}++{{ inventory_name }}++{{ organization }}/hosts/'
        method: POST
        body:
          '{ "variables": {"bla": "sdf"}, "name": "127.0.0.1" }'
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer xq2Xk2ENyuSm9o4MgX0dqQ7gg6J4JO"
        validate_certs: no
        status_code: 204
      delegate_to: localhost


               
