---
- hosts: all
  strategy: free
  gather_facts: no
  tasks:
    - name: wait 1 min
      wait_for:
        timeout: 1

    - name: remove from unpatched
      uri:
        url: 'http://{{ tower_url }}/api/v2/hosts/{{ inventory_hostname }}++{{ inventory_name }}++{{ organization }}/groups/'
        method: POST
        body:
          '{ "id": {{ group_id }}, "name": "unpatched", "disassociate": "true" }'
        body_format: json
        headers:
          Content-Type: application/json
        user: "admin"
        password: "123456"
        validate_certs: no
        status_code: 204
      delegate_to: localhost

    - name: add to patched
      uri:
        url: 'http://{ tower_url }/api/v2/groups/patched++{{ inventory_name }}++{{ organization }}/hosts/'
        method: POST
        body:
          name: "{{ inventory_hostname }}"
        body_format: json
        headers:
          Content-Type: application/json
        user: "admin"
        password: "123456"
        validate_certs: no
        status_code: 204
      delegate_to: localhost     
      
