---
- hosts: all
  strategy: free
  gather_facts: no
  pre_tasks:
    - set_fact:
        failed_hosts_list: []
      run_once: true

  tasks:
    - block:
        - fail:  
      rescue:
        - name: register host to failed hosts
          set_stats:
            data:
              failed_hosts_list: "{{ [ inventory_hostname ] + failed_hosts_list }}"

