---
- hosts: "{{ success_hosts_list }}"
  strategy: free
  gather_facts: no
  pre_tasks:     
    - set_fact:
        current_failed_hosts: []
        tmp: []
      run_once: true

  tasks:
    - block:
      - fail:
          msg: custom fail 1 
        when: "{{ inventory_hostname }}" == "app1-back-prd-1"
      rescue:
      - name: add fail host to list
        set_fact:         
          current_failed_hosts: "{{  [ inventory_hostname ] + current_failed_hosts }}"
    
    - set_fact:
        tmp: "{{ tmp + [{ 'patch capability check': current_failed_hosts }]  }}"
    
    - set_stats:
        data:   
          failed_jobs: "{{ tmp }}"




    # - block:
    #     - fail:  
    #   rescue:
    #     - name: register host to failed hosts
    #       set_stats:
    #         data:
    #           failed_hosts_list: "{{ [ inventory_hostname ] + 1  }}"

