---
- hosts: "{{ success_hosts_list }}"
  strategy: free
  gather_facts: no
  pre_tasks:     
    - set_fact:
        current_failed_hosts: []
        tmp: []
      run_once: true

  tasks:
    - name: set success job list to keep run on them on the patch
      set_fact:         
        current_failed_hosts: "{{  [ inventory_hostname ] + current_failed_hosts }}"

    - set_fact:
        tmp: "{{ tmp + [{ 'patch capability check': current_failed_hosts }]  }}"

    - set_fact:
        tmp: "{{ tmp + [{ 'patch capability check2': current_failed_hosts }]  }}"

    
    # - set_stats:
    #     data:   
    #       tmp: "{{ tmp + [{ 'patch capability check': current_failed_hosts }]  }}"


    - debug:
        var: tmp


    # - block:
    #     - fail:  
    #   rescue:
    #     - name: register host to failed hosts
    #       set_stats:
    #         data:
    #           failed_hosts_list: "{{ [ inventory_hostname ] + 1  }}"

