---
- hosts: "{{ success_hosts_list }}"
  gather_facts: no
  strategy: free
  # serial: 1 
  pre_tasks:     
    - file:
        state: absent
        force: yes
        path: "/tmp/failedHosts.txt"
      delegate_to: 127.0.0.1

    - set_fact:
        job_name: "{{ patch_job }}"
        current_failed_hosts: []
        current_success_hosts_list: "{{ success_hosts_list }}"  
      delegate_to: localhost  
      
  tasks:
    - block:
        - include_role: 
            name: "{{ patch_job }}"
      rescue:
        - name: add fail host to list
          import_tasks: failedhost.yml
            
- hosts: "{{ success_hosts_list }}"
  gather_facts: no
  tasks:     
    - name: apply facts 
      import_tasks: applyResults.yml
