---
- hosts: "{{ success_hosts_list }}"
  gather_facts: no
  strategy: free      
  pre_tasks:     
    - set_fact:
        job_name: "{{ patch_job }}"
        current_failed_hosts: []
        current_success_hosts_list: "{{ success_hosts_list }}"        
      run_once: true

  tasks:
    - name: execute patch role
      include_role: 
        name: "{{ patch_job }}"
      rescue:
        - name: add fail host to list
          include_role:         
            name: patch_facts_handler/failed_host  

    - name: apply facts 
      include_role:         
        name: patch_facts_handler/facts_apply

          

