---
- hosts: "{{ success_hosts_list }}"
  strategy: free
  gather_facts: no
  pre_tasks:     
    - set_fact:
        current_failed_hosts: []
      run_once: true

  tasks:
    - name: set success job list to keep run on them on the patch
      set_fact:         
        current_failed_hosts: "{{  [ inventory_hostname ] + current_failed_hosts }}"
    
    - set_fact:         
        failed_jobs: "{{ failed_jobs +  [{'patch capability check': current_failed_hosts}]  }}"
        failed_jobs: "{{ failed_jobs +  [{'patch capability tmp2': current_failed_hosts}]  }}"


    - debug:
        msg: "{{ failed_jobs }}"


    # - block:
    #     - fail:  
    #   rescue:
    #     - name: register host to failed hosts
    #       set_stats:
    #         data:
    #           failed_hosts_list: "{{ [ inventory_hostname ] + 1  }}"

