---
- hosts: "{{ success_hosts_list }}"
  gather_facts: no
  strategy: free      
  pre_tasks:     
    - set_fact:
        job_name: "patch capability check"
        current_failed_hosts: []
        current_success_hosts_list: "{{ success_hosts_list }}"        
      run_once: true

  tasks:
    - block:
        - debug: 
            msg: "blaa"
          failed_when: inventory_hostname != "localhost"
      rescue:
        - name: add fail host to list
          include_role:         
            name: patch_facts_handler/failed_host  

    - name: apply facts 
      include_role:         
        name: patch_facts_handler/facts_apply


        # - name: job finished facts applier
        #   include_role:
        #     name: patch_facts_handler/facts_apply  
        #   run_once: true
          

