---
- hosts: "{{ success_hosts_list }}"
  gather_facts: no
  pre_tasks:     
    - set_fact:
        job_name: "patch capability check"
        current_failed_hosts: []
        tmp_failed_jobs: []
        tmp_success_hosts_list: "{{ success_hosts_list }}"
      run_once: true

  tasks:
    - block:
        - fail:
            msg: custom fail 1 
          when: inventory_hostname == "app1-back-prd-1"
      rescue:
        - name: add fail host to list
          include_role:         
            name: facts_handler
            apply:
              tags:
               - host_failed

    - name: job finished facts applier
      include_role:
        name: facts_handler
        apply:
          tags:
            - facts_apply
      run_once: true


    # - block:
    #     - fail:  
    #   rescue:
    #     - name: register host to failed hosts
    #       set_stats:
    #         data:
    #           failed_hosts_list: "{{ [ inventory_hostname ] + 1  }}"

