---
- hosts: "{{ success_hosts_list }}"
  gather_facts: no
  strategy: free      
  pre_tasks:     
    - set_fact:
        job_name: "patch capability check"
        current_failed_hosts: []        
      run_once: true

  tasks:
    - block:
        - debug: 
            msg: "blaa"
          failed_when: inventory_hostname != "app1-back-prd-1"
      rescue:
        - name: add fail host to list
          include_role:         
            name: patch_facts_handler/failed_host  

    - set_stats:
        data:
          current_failed_hosts: "{{ current_failed_hosts }}"
          failed_jobs: "{{ failed_jobs + [{ 'patch capability check': current_failed_hosts }]  }}"
        aggregate: no

        # - name: job finished facts applier
        #   include_role:
        #     name: patch_facts_handler/facts_apply  
        #   run_once: true
          

