---
- hosts: all
  strategy: free
  gather_facts: no
  tasks:
    - name: wait 1 min
      wait_for:
        timeout: 1200
      delegate_to: localhost


    - name: remove from unpatched
      uri:
        url: 'http://{{ tower_url }}/api/v2/hosts/{{ inventory_hostname }}++{{ inventory_name }}++{{ organization }}/groups/'
        method: POST
        body:
          '{ "id": {{ group_id }}, "name": "unpatched", "disassociate": "true" }'
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer xq2Xk2ENyuSm9o4MgX0dqQ7gg6J4JO"
        validate_certs: no
        status_code: 204
      delegate_to: localhost

    - name: add to patched
      uri:
        url: 'http://{{ tower_url }}/api/v2/groups/patched++{{ inventory_name }}++{{ organization }}/hosts/'
        method: POST
        body:
          name: "{{ inventory_hostname }}"
        body_format: json
        headers:
          Content-Type: application/json       
          Authorization: "Bearer xq2Xk2ENyuSm9o4MgX0dqQ7gg6J4JO"
        validate_certs: no
        status_code: 204
      delegate_to: localhost     
      
