---
- hosts: all
  gather_facts: no
  pre_tasks:
    - set_fact:
        failed_jobs: []
        success_hosts_list: []
      run_once: true

  tasks:
    - name: set success job list to keep run on them on the patch
      set_fact:
        success_hosts_list: "{{ [ inventory_hostname ] + success_hosts_list }}"
    
    - name: set success host list and failed jobs list that will contains what hosts failed on which jobs
      set_stats:
        data:
          failed_jobs: []
          success_hosts_list: "{{ success_hosts_list }}"

