---
- hosts: all
  gather_facts: no
  pre_tasks:
    - set_fact:
        failed_jobs: []
        success_hosts_list: []
      run_once: true

  tasks:
    - name: set failed jobs object, it will contain all jobs that hosts has failed on them, and the hosts list the failed on each job
      set_stats:
        data:
          failed_jobs: []
      run_once: true

    - name: set success job list to keep run on them on the patch
      set_fact:
        success_hosts_list: "{{ [ inventory_hostname ] + success_hosts_list }}"
    
    - name: set success host list to keep running on them during the patch
        data:
          success_hosts_list: "{{ success_hosts_list }}"
      run_once: true

