---
 - debug:
     var: hostvars['localhost']
 
  - debug:
     var: hostvars['localhost']["ansible_check_mode"]

 - debug:
     var: hostvars['localhost']["current_success_hosts_list"]

 - set_stats:
     data:
       success_hosts_list: "{{ hostvars['localhost']['current_success_hosts_list'] }}"
       failed_jobs: "{{ failed_jobs + [{ patch_job: hostvars['localhost']['current_failed_hosts'] }]  }}"
     aggregate: no
